Improve CI
Odonno/surrealdb-migrations pull request #22
Opened 2023-05-20 06:17 UTC by Roms1383

Related to #5

2023-05-20 06:25 UTC, Roms1383 commented
I have a suggestion regarding the `publish crate` job in `main` `release` workflow: usually you might want to run everything on every commit (`check` / `build` / `format` / `lint`) and only run `release` related job steps on `main` once all the other jobs have succeeded. Would you like me to make the appropriate changes in that regard ?

2023-05-20 07:01 UTC, Odonno commented
Hi @Roms1383 

Thank you for tackling this issue. With your help, I want to improve the whole CI, improve quality/reliability and reduce build time as much as possible.

Indeed, I want the `publish crate` to run once everything succeed. That's why it's the last command in the job. I suppose you want to make a separate/dependent job? If so, feel free to do so.

I already have some question regarding the current state of your PR:

* [ ] Should the cargo config file be named `config.toml`? (I see the extension is missing)
* [ ] Is `git-fetch-with-cli = true` supposed to fix the `error: failed to verify the checksum of surrealdb v1.0.0-beta.9+20230402` error?
* [ ] I hope it is not too much to ask but `format` and `lint` are currently not parts of the CI. Is it possible for you to add them?
* [ ] Same question for `check` step if you think that's necessary to add it

Anyway, thanks again for doing this.

2023-05-20 10:46 UTC, Roms1383 commented
> Should the cargo config file be named config.toml? (I see the extension is missing)

cargo actually reads both (see [config](https://doc.rust-lang.org/cargo/reference/config.html)), but you're right the preferred  one is with `.toml` so I updated it.

> Is git-fetch-with-cli = true supposed to fix the error: failed to verify the checksum of surrealdb v1.0.0-beta.9+20230402 error?

Yes, as far as I remember there's an issue with semver in dependencies version at the moment. I fixed it on my repo by temporarily specifying this and the git path (see e1becfd).

> I hope it is not too much to ask but format and lint are currently not parts of the CI. Is it possible for you to add them?

Of course! :)

> Same question for check step if you think that's necessary to add it

Added it too!

2023-05-20 10:50 UTC, Roms1383 commented
By the way you don't necessarily need to use char emoji directly in commit messages, but you can type them as text like`:emoji:` instead ? See [gitmoji](https://gitmoji.dev/).

2023-05-20 10:55 UTC, Roms1383 commented
How do you usually like to trigger releases ?
By committing a tag on `main` branch, or via Github releases ?

2023-05-20 11:49 UTC, Odonno commented
> By the way you don't necessarily need to use char emoji directly in commit messages, but you can type them as text like`:emoji:` instead : see [gitmoji](https://gitmoji.dev/).

I am a lazy guy, I click on the icon to copy/paste the emoji.

2023-05-20 11:52 UTC, Odonno commented
> How do you usually like to trigger releases ? By committing a tag on `main` branch, or via Github releases ?

My current process is the following:

* Change the version in `Cargo.toml` via a commit, and publish a new crate version only if a new version is detected on `main` branch (main workflow)
* Manually create a GitHub release following the pushed commit to `main`

I am comfortable to have a manual process for the moment. I could change it if you have provide an interesting solution.

2023-05-20 12:33 UTC, Roms1383 commented
Mine is similar:
- bump version in `Cargo.toml` on `main`, then commit + push
- add `tag` on `main` then commit + push and let workflows do the rest (build > bundle artifacts > create draft github release)

and if everything goes fine I manually update the draft release to a published release.

For example in this [release workflow](https://github.com/Roms1383/mdbook-codeblocks/blob/main/.github/workflows/release.yml).

2023-05-20 14:32 UTC, Odonno commented
So, you would move the publish crate step to the release workflow? If this is your idea, I am ok doing that.

2023-05-20 14:58 UTC, Roms1383 commented
Should be good to review :)

2023-05-20 15:11 UTC, Roms1383 reviewed
Ok I gave a couple more context.

2023-05-20 15:11 UTC, Roms1383 commented on Cargo.toml
> +surrealdb = { git = "https://github.com/surrealdb/surrealdb.git", tag = "v1.0.0-beta.9+20230402" }
this is temporary until https://github.com/rust-lang/cargo/issues/7180 is fixed or until surrealdb bumps to next non-semver version.

2023-05-20 15:11 UTC, Roms1383 commented on .cargo/config.toml
> +git-fetch-with-cli = true
this is temporary until https://github.com/rust-lang/cargo/issues/7180 is fixed or until surrealdb bumps to next non-semver version.

2023-05-20 15:11 UTC, Roms1383 commented on src/scaffold/schema.rs
> -    if schema.tables.len() <= 0 {
here `.len()` is a `usize` so it cannot be under `0`, then `clippy` suggests `is_empty` for readability.

2023-05-21 09:52 UTC, Odonno commented on src/scaffold/schema.rs
> -    if schema.tables.len() <= 0 {
I should use `isEmpty()` instead of `len()` whenever I can. That's on me. Thanks for the fix.

2023-05-21 09:53 UTC, Odonno commented on Cargo.toml
> +surrealdb = { git = "https://github.com/surrealdb/surrealdb.git", tag = "v1.0.0-beta.9+20230402" }
Can you target the `main` branch so we can fix #20 ?

2023-05-21 10:09 UTC, Odonno requested changes
Good job on this. Also, when you are done with all the changes, can you rebase your commit history to clean it?

2023-05-21 10:09 UTC, Odonno commented on .github/workflows/main.yml
> +on: push
Why remove the constraint on "main" branch? The `main` workflow is for when pushing to `main`. The `pull-request` worklow if for when we push to a PR branch.

If the 2 workflows are the same, we can remove the `pull-request` and have a single `main` workflow.

2023-05-21 10:09 UTC, Odonno commented on .github/workflows/main.yml
> +    if: github.ref == 'refs/heads/main'
Should not be here, per the last review comment.

2023-05-21 10:09 UTC, Odonno commented on src/config/core.rs
> +#[allow(dead_code)]
I assume the CI fails if there is dead code? I need to refactor the code and make an underlying lib project that can be used by either `main.rs` or `lib.rs`. If it fails, I'm ok to leave it. Anyway, this is a temporary solution.

2023-05-21 10:13 UTC, Odonno commented
I suppose there are many changes in the code due to `cargo check`? I am using the `rust-lang.rust-analyzer` vscode extension. Do you recommend a better extension and/or is it compatible with `cargo check`?

2023-05-21 13:48 UTC, Roms1383 commented on Cargo.toml
> +surrealdb = { git = "https://github.com/surrealdb/surrealdb.git", tag = "v1.0.0-beta.9+20230402" }
why would you prefer targeting `main` branch ? usually it's better to target `tag`, if I understand correctly.

2023-05-21 13:49 UTC, Roms1383 commented on .github/workflows/main.yml
> +on: push
Yes actually I came to the same conclusion, that `pull-request` workflow was redundant, let me remove it.

2023-05-21 13:54 UTC, Roms1383 commented on .github/workflows/main.yml
> +    if: github.ref == 'refs/heads/main'
well this one is because you might not want coverage on each and every push to each and every branch, hence why I initially restricted it to tags on `main`.

2023-05-21 13:55 UTC, Roms1383 commented on src/config/core.rs
> +#[allow(dead_code)]
Yes indeed there's a bunch of dead or duplicated functions (e.g. `create_surrealdb_client` which appears both in lib and tests alike). Putting annotations allow clippy to succeed, and are good reminders that code needs to be cleaned.

2023-05-21 13:56 UTC, Roms1383 commented
> I suppose there are many changes in the code due to cargo check? I am using the rust-lang.rust-analyzer vscode extension. Do you recommend a better extension and/or is it compatible with cargo check?

That's the recommended one, I use it too, it should be fine.

2023-05-21 14:01 UTC, Roms1383 commented on .github/workflows/main.yml
> +on: push
done in 7ff2aba

2023-05-21 14:02 UTC, Roms1383 commented on .github/workflows/release.yml
> +      - name: Publish crate
done in 22fe4b9

2023-05-21 14:02 UTC, Roms1383 commented
> Good job on this. Also, when you are done with all the changes, can you rebase your commit history to clean it?

done in 63e8d45 and 535fa89

2023-05-21 14:07 UTC, Roms1383 commented on .github/workflows/release.yml
> +      - name: Publish crate
let me know if I should remove the restriction on `tag` too.

2023-05-22 17:51 UTC, Odonno commented on Cargo.toml
> +surrealdb = { git = "https://github.com/surrealdb/surrealdb.git", tag = "v1.0.0-beta.9+20230402" }
There is currently an important fix that lives in the `main`. Without that, the lib is pretty useless in production. I know this is a bad practice but it is temporary until the beta 10 version.

2023-05-23 01:30 UTC, Roms1383 commented
Ok please hold on a bit @Odonno, currently rebasing and then I'll have to address your reviews :)

By the way I have a question: is there a reason to duplicate methods `create_surrealdb_client`, `create_surrealdb_connection`, `sign_in` and `set_namespace_and_database` in `surrealdb.rs` files both `src` and `tests` ? They look identical at first sight.

2023-05-23 02:46 UTC, Roms1383 commented on Cargo.toml
> +surrealdb = { git = "https://github.com/surrealdb/surrealdb.git", tag = "v1.0.0-beta.9+20230402" }
Ok I've done the change locally: pinning on `main` is failing the tests. I'm currently investigating.

2023-05-23 03:19 UTC, Roms1383 commented on Cargo.toml
> +surrealdb = { git = "https://github.com/surrealdb/surrealdb.git", tag = "v1.0.0-beta.9+20230402" }
Do you have an idea why `tarpaulin` is failing because of missing files / folders ?

Please look at this [action run on my fork](https://github.com/Roms1383/surrealdb-migrations/actions/runs/5052684992)
This is the action run for:
- commit ffc2654
- prior to bumping `surrealdb` to `main`
- with `tarpaulin` enabled from `pull_request`).

2023-05-23 04:19 UTC, Roms1383 commented on Cargo.toml
> +surrealdb = { git = "https://github.com/surrealdb/surrealdb.git", tag = "v1.0.0-beta.9+20230402" }
Otherwise typical error I get in failed tests when switching on `main` is:

failures:

```sh
---- cli::apply::up::apply_initial_migrations stdout ----
Error: Unexpected failure.
code-1
stderr=
Error: There was a problem with the database: Parse error on line 5 at character 28 when parsing \'TYPE record<user> ASSERT $value != NONE;
DEFINE FIELD created_at ON post TYPE datetime VALUE $before\'

Caused by:
    There was a problem with the database: Parse error on line 5 at character 28 when parsing \'TYPE record<user> ASSERT $value != NONE;
    DEFINE FIELD created_at ON post TYPE datetime VALUE $before\'
```
Still looking out why ^^

2023-05-23 07:37 UTC, Roms1383 commented on Cargo.toml
> +surrealdb = { git = "https://github.com/surrealdb/surrealdb.git", tag = "v1.0.0-beta.9+20230402" }
Ok waiting for ur feedback on both.

I couldn't figure out which file is actually missing in `tarpaulin` coverage, and it's especially weirder since it works just fine on my local.

On the other hand, I've tried an extensive bunch of stuff to find out why when switching to `surrealdb main` there are parse errors, till now unsuccessfully.

2023-05-23 09:58 UTC, Odonno commented
They are pretty much the same functions. Indeed, some code is duplicated between `src` and `tests`. I want to improve the architecture with a dedicated library. I will create a new issue for this issue. Anyway, I don't think this change should fit in this PR.

2023-05-23 10:53 UTC, Odonno commented on Cargo.toml
> +surrealdb = { git = "https://github.com/surrealdb/surrealdb.git", tag = "v1.0.0-beta.9+20230402" }
Ok, I looked at the code of `surrealdb` and record type now looks like this `record<user>` or this `record<type1 | type2 | type3>`. I beleive they are using the discriminated union notation from TypeScript. Not sure what to do here, either

* stick to the current beta-9 version with the existing bug
* or move to a `0.10.X` release right now by changing the templates

I think the best move would be to rollback to beta-9 for now, merge the PR, release the v0.9.6 and then make changes to release preview for `0.10.X`.

2023-05-23 10:57 UTC, Roms1383 commented on Cargo.toml
> +surrealdb = { git = "https://github.com/surrealdb/surrealdb.git", tag = "v1.0.0-beta.9+20230402" }
I was wondering exactly the same, and I even tried to change `record(T)` for `record<T>` everywhere but it didn't fix (except if I missed some autogenerated part, that could be).

And concerning `tarpaulin`, any idea why it complains over and over that `Error: No such file or directory` ?

2023-05-23 10:58 UTC, Roms1383 commented
> They are pretty much the same functions. Indeed, some code is duplicated between src and tests. I want to improve the architecture with a dedicated library. I will create a new issue for this issue. Anyway, I don't think this change should fit in this PR.

Sounds good to me 👌

2023-05-23 10:59 UTC, Odonno commented on Cargo.toml
> +surrealdb = { git = "https://github.com/surrealdb/surrealdb.git", tag = "v1.0.0-beta.9+20230402" }
Regarding the missing files/folder. I have now idea. If the code is strictly similar to `main` branch, it should work. The CI tests job is not 100% reliable, you can try to re-run the job and see if you have a different result.

2023-05-23 12:45 UTC, Roms1383 commented on Cargo.toml
> +surrealdb = { git = "https://github.com/surrealdb/surrealdb.git", tag = "v1.0.0-beta.9+20230402" }
Tests now pass on `main`, currently investigating about `tarpaulin`.

2023-05-23 14:29 UTC, Roms1383 commented
Ready for review @Odonno 🎉 
CI is running [on fork over there](https://github.com/Roms1383/surrealdb-migrations/actions/runs/5058495735).

2023-05-23 15:11 UTC, Roms1383 commented
As a side note, a recurrent warning in the console inform that `license-file` and `license` keys are redundant in `Cargo.toml` : whichever would you like to keep ?

2023-05-23 15:32 UTC, Odonno commented
> As a side note, a recurrent warning in the console inform that `license-file` and `license` keys are redundant in `Cargo.toml` : whichever would you like to keep ?

Yes, I know. I started to play with `license-file` but instead of showing `MIT` in the crates.io website, it showed `unknown` or something like that. I added `license = MIT` to force the display of MIT on this website. Not sure what is the best option.

2023-05-23 15:38 UTC, Odonno commented on .github/workflows/main.yml
> +    if: github.ref == 'refs/heads/main'
Branch coverage is the detection of every paths in a codebase. Like when you encounters an `if`. Without branch coverage, having a single test that goes in the if, whether the condition is `true` or `false`, will be 100% valid coverage. This is a nice feature to detect the different cases but I can work without it for the moment.

However diff/patch is extremely useful because it allows you to see if merging a branch will increase or decrease the overall coverage of the codebase, like you can see on other PR.

2023-05-23 15:40 UTC, Odonno commented on Cargo.toml
> +surrealdb = { git = "https://github.com/surrealdb/surrealdb.git", tag = "v1.0.0-beta.9+20230402" }
Yes, I know the CI for tests is very long. I hope we can find ways to reduce the build time in the future.

2023-05-23 15:40 UTC, Roms1383 commented
You could just keep `license = MIT` without deleting the `LICENSE` file at the root of the repo, maybe ?
This way `crates.io` shows up correctly and user still have access to your `LICENSE` file.
or just look at how other popular crates out there handle that :)
It's out of the scope of this PR anyway.

As you can see from [last 2 Actions runs](https://github.com/Roms1383/surrealdb-migrations/actions), we're green & ready for review ! 🚀

2023-05-23 16:05 UTC, Odonno requested changes

2023-05-23 16:05 UTC, Odonno commented on tests/library/validate_version_order.rs
> +            if first_migration_file.exists() {
I suppose the `if` should not be here. If the `remove_file` function fails, the test should fail if we can't find the file.

2023-05-23 16:05 UTC, Odonno commented on tests/helpers/io.rs
> +    if dir.is_dir() && dir.exists() {
Return an error if `dir` is not a dir?

2023-05-23 16:05 UTC, Odonno commented on tests/helpers/io.rs
> +    if migrations_files_dir.is_dir() && migrations_files_dir.exists() {
Return an error if `migrations_files_dir` is not a dir?

2023-05-23 16:05 UTC, Odonno commented on tests/helpers/io.rs
> +    if schemas_files_dir.is_dir() && schemas_files_dir.exists() {
Return an error if `schemas_files_dir` is not a dir?

2023-05-23 16:07 UTC, Odonno commented
> You could just keep `license = MIT` without deleting the `LICENSE` file at the root of the repo, maybe ? This way `crates.io` shows up correctly and user still have access to your `LICENSE` file. or just look at how other popular crates out there handle that :) It's out of the scope of this PR anyway.
> 
> As you can see from [last 2 Actions runs](https://github.com/Roms1383/surrealdb-migrations/actions), we're green & ready for review ! 🚀

Review is done. There are many changes in this PR so I detected some things to change.

I will remove `license-file` property then.

2023-05-23 23:15 UTC, Roms1383 commented on .github/workflows/main.yml
> +    if: github.ref == 'refs/heads/main' || github.event_name != 'pull_request'
all or?

2023-05-23 23:18 UTC, Roms1383 commented on .github/workflows/main.yml
> +          args: "--engine llvm --target-dir target/tarpaulin"
on subsequent builds (after the first one) it's making `coverage` faster (30min is  way too long)

2023-05-23 23:21 UTC, Roms1383 commented on .github/workflows/release.yml
> +    if: github.ref == 'refs/heads/main' && startsWith(github.ref, 'refs/tags/v')
you do not want to publish on each and every commit to each and every branch, do you?

2023-05-23 23:39 UTC, Roms1383 commented on .github/workflows/main.yml
> +          args: "--engine llvm --target-dir target/tarpaulin"
I linked related articles in the commit, if you want to read them out.

2023-05-23 23:41 UTC, Roms1383 commented on Cargo.toml
> +anyhow = "1"
yes, for most of the crates that's the case, but usually for "foundation" crates you can be confident that they are not gonna push breaking changes on a patch or a minor. I don't mind setting entire semver tho.

2023-05-23 23:42 UTC, Roms1383 commented on Cargo.toml
> +rust-ini = "0.19"
If there was any breaking change your tests would have caught it.

2023-05-23 23:43 UTC, Roms1383 commented on samples/wasm/rsw-hello/src/lib.rs
> +        .map(|post| serde_wasm_bindgen::to_value(&post).unwrap())
That's what `clippy` suggested, I just applied the suggestion. To check it out, simply revert the change locally and re-run `cargo clippy`.

2023-05-23 23:43 UTC, Roms1383 commented on src/io.rs
> +    if let Some(DirEntryValue::String(value)) = f.get(&entry_attribute) {
Same, I just applied the `clippy` suggestion here. If there was any problem, your tests would have failed.

2023-05-23 23:46 UTC, Roms1383 commented on tests/library/validate_version_order.rs
> +            if first_migration_file.exists() {
I can revert that. I wrongfully thought the `No such file or directory` error was related, while it was due to missing SurrealDB in workflow.

2023-05-23 23:47 UTC, Roms1383 commented on tests/helpers/io.rs
> +    if dir.is_dir() && dir.exists() {
Same as my previous comment: I can revert that. I wrongfully thought the No such file or directory error was related, while it was due to missing SurrealDB in workflow.

2023-05-23 23:47 UTC, Roms1383 commented on tests/helpers/io.rs
> +    if migrations_files_dir.is_dir() && migrations_files_dir.exists() {
Same as my previous comment: I can revert that. I wrongfully thought the No such file or directory error was related, while it was due to missing SurrealDB in workflow.

2023-05-23 23:47 UTC, Roms1383 commented on tests/helpers/io.rs
> +    if schemas_files_dir.is_dir() && schemas_files_dir.exists() {
Same as my previous comment: I can revert that. I wrongfully thought the No such file or directory error was related, while it was due to missing SurrealDB in workflow.

2023-05-23 23:53 UTC, Roms1383 commented on tests/helpers/io.rs
> +    if schemas_files_dir.is_dir() && schemas_files_dir.exists() {
reverted in e01c565

2023-05-23 23:53 UTC, Roms1383 commented on tests/helpers/io.rs
> +    if migrations_files_dir.is_dir() && migrations_files_dir.exists() {
reverted in e01c565

2023-05-23 23:53 UTC, Roms1383 commented on tests/helpers/io.rs
> +    if dir.is_dir() && dir.exists() {
reverted in e01c565

2023-05-23 23:58 UTC, Roms1383 commented on tests/library/validate_version_order.rs
> +            if first_migration_file.exists() {
reverted in 400619f

2023-05-24 00:03 UTC, Roms1383 commented on src/io.rs
> +    if let Some(DirEntryValue::String(value)) = f.get(&entry_attribute) {
By the way

```rs
if let Some(DirEntryValue::Boolean(value)) = f.get(&entry_attribute) {
    return Some(value);
}
None
```

and

```rs
match f.get(&entry_attribute) {
    Some(DirEntryValue::Boolean(value)) => Some(value),
    _ => None,
}
```

are strictly equivalent.

2023-05-24 00:04 UTC, Roms1383 commented on src/io.rs
> +    if let Some(DirEntryValue::String(value)) = f.get(&entry_attribute) {
standardised in 338b5db

2023-05-24 00:09 UTC, Roms1383 commented on samples/wasm/rsw-hello/src/lib.rs
> +        .map(|post| serde_wasm_bindgen::to_value(&post).unwrap())
Ah sorry, it's actually not `clippy` which yields the warning, but a build.
You can reproduce by running `(cd samples/wasm/rsw-hello && wasm-pack build --target web)` and here's what you get:

```sh
warning: use of deprecated associated function `wasm_bindgen::JsValue::from_serde`: causes dependency cycles, use `serde-wasm-bindgen` or `gloo_utils::format::JsValueSerdeExt` instead
```

2023-05-24 00:13 UTC, Roms1383 commented on .github/workflows/main.yml
> +        run: (cd samples/wasm/rsw-hello && wasm-pack build --target web)
done in 8d91ab8

2023-05-24 00:26 UTC, Roms1383 commented on Cargo.toml
> +anyhow = "1"
done in f4e1ec6

2023-05-24 00:26 UTC, Roms1383 commented on Cargo.toml
> +rust-ini = "0.19"
done in f4e1ec6

2023-05-24 00:29 UTC, Roms1383 commented on .github/workflows/main.yml
> +          args: "--engine llvm --target-dir target/tarpaulin"
I added `--skip-clean` as suggested in the related articles, as `--target-dir` alone this does not seem to speed up the build (see running actions duration on my fork).

2023-05-24 00:30 UTC, Roms1383 commented on .github/workflows/main.yml
> +          args: "--engine llvm --target-dir target/tarpaulin"
in my own book, waiting 30min for code coverage is just unacceptable 😄

2023-05-24 00:40 UTC, Roms1383 commented on .github/workflows/main.yml
> +    if: github.ref == 'refs/heads/main' || github.event_name != 'pull_request'
removed in 4b466ea

2023-05-24 01:06 UTC, Roms1383 commented on .github/workflows/main.yml
> +          args: "--engine llvm --target-dir target/tarpaulin"
as it turns out from latest runs, `--target-dir` / `--skip-clean` does not seem to speed up the build anytime 😒 ...

2023-05-24 08:15 UTC, Odonno commented on .github/workflows/main.yml
> +          args: "--engine llvm --target-dir target/tarpaulin"
https://identeco.de/en/blog/speed-up-rust-ci-pipelines-that-use-tarpaulin/

I understand now. So setting `target-dir` allows separate build artifacts between a normal build and a test build.

It seems that the cache is not saved between those builds because the `RUSTFLAGS` between tarpaulin and normal builds is different, per the article. The CI should use the same flag to make use of the cache efficienctly.

`--skip-clean` seams useless.

It seems you can configure a lot in `tarpaulin.toml` (like the target dir). I would like to have everything in this file, so that we have the same configuration locally.

2023-05-24 11:31 UTC, Roms1383 commented on .github/workflows/main.yml
> +          args: "--engine llvm --target-dir target/tarpaulin"
> I understand now. So setting target-dir allows separate build artifacts between a normal build and a test build.

Yes indeed.

> It seems that the cache is not saved between those builds because the RUSTFLAGS between tarpaulin and normal builds is different, per the article. The CI should use the same flag to make use of the cache efficienctly.

The article says "one way or the other", but it could be worth trying.

> --skip-clean seams useless.

Agreed.

> It seems you can configure a lot in tarpaulin.toml (like the target dir). I would like to have everything in this file, so that we have the same configuration locally.

I won't be available for a couple of hours, but please go ahead and give it a try right if you want :)

2023-05-24 11:51 UTC, Odonno commented on .github/workflows/main.yml
> +          args: "--engine llvm --target-dir target/tarpaulin"
Yeah. I re-read that article and read the other articles. Reducing build times seems to be a really complex topic.

I am aware that, for this kind of project, tests should run in 3 minutes and not 30 minutes. I think this is an infrastructure issue and that it can be improved in the future. In the meantime, we can rollback this changes and I can create an issue regarding tests build times.

What do you think?

2023-05-24 13:04 UTC, Odonno commented on .github/workflows/main.yml
> +          args: "--engine llvm --target-dir target/tarpaulin"
Why not?

2023-05-24 14:06 UTC, Roms1383 commented on .github/workflows/main.yml
> +          args: "--engine llvm --target-dir target/tarpaulin"
So you're suggesting to completely remove coverage job or? Not sure I understand.

2023-05-24 14:09 UTC, Roms1383 commented on .github/workflows/main.yml
> +          args: "--engine llvm --target-dir target/tarpaulin"
If you want you can reach [me out on Discord](Roms1383#0211) to discuss it briefly too.

2023-05-24 18:25 UTC, Odonno requested changes
I think we are close to the end. 👍

2023-05-24 18:25 UTC, Odonno commented on .github/workflows/example.yml
> +on: push
Add path filter on `samples/**`

https://stackoverflow.com/a/63822945

2023-05-24 18:25 UTC, Odonno commented on .github/workflows/example.yml
> +name: Example Workflow
Must be `Samples Workflow` to use the same name as the `samples` folder. Also rename the file name.

2023-05-25 00:48 UTC, Roms1383 commented on .github/workflows/example.yml
> +on: push
the problem if you do that, is whenever you'll make a change on `surrealdb-migrations` which breaks `samples`, then you won't see it until your next push to `samples` (which generally means 'never' since sample do not get changed very often).

2023-05-25 00:50 UTC, Roms1383 commented on .github/workflows/example.yml
> +name: Example Workflow
done in 4160075

2023-05-25 01:09 UTC, Roms1383 commented on .github/workflows/example.yml
> +name: Example Workflow
and renamed in 1d24614

2023-05-25 01:15 UTC, Roms1383 commented on .github/workflows/example.yml
> +on: push
what I did instead is to ignore some paths unrelated to `samples` in 811db37

2023-05-25 09:21 UTC, Odonno commented on .github/workflows/example.yml
> +on: push
Ah, yes, you're right.

2023-05-25 09:23 UTC, Odonno approved these changes
Seems good to me. Thank you for your effort.

2023-05-26 10:36 UTC, merged