Build docker image for multiple processor architectures
Odonno/surrealdb-migrations pull request #94
Opened 2024-11-07 11:39 UTC by akkie

This is a proof of concept PR. It currently pushes to the GitHub docker registry. Maybe you can activate the pipeline to see if it works. Later you can then change it to push to docker hub.

I droped the [muslrust](https://github.com/clux/muslrust) image in favour of the rust image. This is also noted in the readme: https://github.com/clux/muslrust?tab=readme-ov-file#alternatives

> [official rust image](https://hub.docker.com/_/rust) can target add and easily cross-build when not needing [C libraries](https://github.com/clux/muslrust?tab=readme-ov-file#c-libraries)

I don't think that you need C libs which muslrust provides.

2024-11-08 06:13 UTC, senpro-ingwersenk commented
LGTM!
Took the opportunity (...or excuse :p) to learn a little more about Github workflows. I was dead sure they had native ARM runners...but guess not; there's QEMU and "runs-on" workflows everywhere o.o

2024-11-16 13:28 UTC, akkie commented
I have updated the docker workflow and separated it from the existing release workflow. Also built it based on the official [Docker tutorial](https://docs.docker.com/build/ci/github-actions/cache/#cache-backend-api), because there was an issue with the old workflow where the arch64 images was not published to the registry. It also uses directly the Docker Hub log in now. Only the env variables with the credentials needs to be set.

2025-05-04 17:46 UTC, Odonno requested changes

2025-05-04 17:46 UTC, Odonno commented on Dockerfile
> +RUN mkdir -p /tmp/bin && cp /volume/target/$(cat /tmp/target)/release/surrealdb-migrations /tmp/bin/
suggestion: split line and use `COPY` command

2025-05-04 17:46 UTC, Odonno commented on .github/workflows/release-docker.yml
> +  release:
todo: remove this file and add a new job in the `release` template

2025-05-04 17:46 UTC, Odonno commented on .github/workflows/release-docker.yml
> +        if: matrix.platform != 'linux/amd64'
question: does that change anything?

2025-05-04 17:46 UTC, Odonno commented on .github/workflows/release-docker.yml
> +name: Build and Deploy
todo: can also add a job to validate Docker run in the `main` template? (without publishing to Docker Hub)

2025-05-04 17:46 UTC, Odonno commented on .github/workflows/release-docker.yml
> +  docker-merge:
question: I might be wrong but that seems overcomplicated compared to what is explained in the docs. See a working example here: https://github.com/surrealdb/surrealist/blob/fb1e2e269e5d20f405d715680e071e70fc4c42f3/.github/workflows/push-release.yaml#L33C3-L65C70

2025-05-04 17:46 UTC, Odonno commented on Dockerfile
> +RUN case "$TARGETPLATFORM" in \
praise: I did not find another way to do this. I suppose this is the smartest way to do this.

2025-05-05 14:39 UTC, akkie commented on .github/workflows/release-docker.yml
> +  docker-merge:
Your linked example do not create a multi arch image. It only builds for linux/amd64: https://hub.docker.com/r/surrealdb/surrealist/tags

It's implemented based on: https://docs.docker.com/build/ci/github-actions/multi-platform/#distribute-build-across-multiple-runners

2025-05-05 14:42 UTC, akkie commented on .github/workflows/release-docker.yml
> +        if: matrix.platform != 'linux/amd64'
This is not required anymore because GitHub now supports arm based runners for open source projects. Previously it was used to only install QEMU when building an arm image.

2025-05-05 14:47 UTC, akkie commented on Dockerfile
> +RUN mkdir -p /tmp/bin && cp /volume/target/$(cat /tmp/target)/release/surrealdb-migrations /tmp/bin/
I would not change that because this should be placed in one docker layer. It doesn't really make sense to have an own layer with the created dir. I'm also not sure if the cat command is expanded during COPY.

2026-04-11 10:17 UTC, closed without merging